CLASSES_TO_BLURR:
  - person
  - car
  - van
  - bus
  - truck

# If value is 0, no blur will be applied
# If value is 1, the image part will be completely blurred
BLURR_INTENSITY: 0.7

# NAS model to use
NAS_MODEL: yolo_nas_l

# Azure credentials
INPUT_CONNECTION_STRING:
INPUT_CONTAINER_NAME:
